export enum brandMap {
    GPU = 0,
    GPUAdapter = 1,
    GPUDevice = 2,
    GPUBuffer = 3,
    GPUCommandEncoder = 4,
    GPUCommandBuffer = 5,
    GPUQueue = 6,
    GPUTexture = 7,
    GPUShaderModule = 8,
    GPURenderPipeline = 9,
    GPURenderPassEncoder = 10,
    GPUTextureView = 11,
    GPUBindGroupLayout = 12,
    GPUBindGroup = 13,
    GPUSampler = 14,
};
